service: snakecharmvr
package:
  individually: false

provider:
  name: aws
  stage: prod
  runtime: python3.6
  region: us-east-1

functions:
  snakecharmvr:
    name: snakecharmvr
    handler: SnakeCharmvrWebApp.lambda_handler
    description: Deliver SnakeCharmvr
    memorySize: 128
    timeout: 30
    events:
      - http:
          path: /{proxy+}
          method: get

plugins:
  - serverless-python-requirements
